{
 "title": "InfluxDB SP16C Dashboard",
 "tags": [
  "influxdb",
  "sp16C"
 ],
 "time": { "from": "2025-10-23T15:33:18.185Z", "to": "2025-10-23T15:46:31.611Z" },
 "panels": [
  {
   "title": "SP16C_4R_TRA_POS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"demo-bucket\")\n  |> range(start: -1000h)\n  |> filter(fn: (r) => r._measurement == \"experiment_opc\")\n  |> filter(fn: (r) => r._field == \"SP16C.SP16C_MON_REF_4R_TRA_POS\")\n  |> aggregateWindow(every: 5s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "SP16C_4R_A_STAR",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 5, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"demo-bucket\")\n  |> range(start: -1000h)\n  |> filter(fn: (r) => r._measurement == \"experiment_opc\")\n  |> filter(fn: (r) => r._field == \"SP16C.SP16C_MON_REF_4R_A_STAR\")\n  |> aggregateWindow(every: 5s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "SP16C_4R_B_STAR",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 14, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"demo-bucket\")\n  |> range(start: -1000h)\n  |> filter(fn: (r) => r._measurement == \"experiment_opc\")\n  |> filter(fn: (r) => r._field == \"SP16C.SP16C_MON_REF_4R_B_STAR\")\n  |> aggregateWindow(every: 5s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n\n"
    }
   ]
  }
 ]
}